
import { StudentExamResult } from '@/types';

export const mockStudentData: StudentExamResult[] = [
  // Deneme 1
  {
    exam_name: 'LGS Deneme Sınavı 1',
    date: '2024-04-15',
    class: '8-A',
    student_no: 101,
    student_name: 'Ayşe Yılmaz',
    toplam_dogru: 75,
    toplam_yanlis: 15,
    toplam_net: 70,
    toplam_puan: 420,
    turkce: { dogru: 18, yanlis: 2, net: 17.33, kazanimlar: [ { konu: "Sözcükte Anlam", sonuc: "D"}, { konu: "Cümlede Anlam", sonuc: "Y"} ] },
    tarih: { dogru: 9, yanlis: 1, net: 8.67, kazanimlar: [] },
    din: { dogru: 8, yanlis: 2, net: 7.33, kazanimlar: [] },
    ing: { dogru: 9, yanlis: 1, net: 8.67, kazanimlar: [] },
    mat: { dogru: 15, yanlis: 5, net: 13.33, kazanimlar: [ { konu: "Üslü İfadeler", sonuc: "D"}, { konu: "Kareköklü İfadeler", sonuc: "Y"} ] },
    fen: { dogru: 16, yanlis: 4, net: 14.67, kazanimlar: [] },
  },
  {
    exam_name: 'LGS Deneme Sınavı 1',
    date: '2024-04-15',
    class: '8-A',
    student_no: 102,
    student_name: 'Mehmet Kaya',
    toplam_dogru: 80,
    toplam_yanlis: 10,
    toplam_net: 76.67,
    toplam_puan: 450,
    turkce: { dogru: 19, yanlis: 1, net: 18.67, kazanimlar: [] },
    tarih: { dogru: 10, yanlis: 0, net: 10, kazanimlar: [] },
    din: { dogru: 9, yanlis: 1, net: 8.67, kazanimlar: [] },
    ing: { dogru: 10, yanlis: 0, net: 10, kazanimlar: [] },
    mat: { dogru: 16, yanlis: 4, net: 14.67, kazanimlar: [] },
    fen: { dogru: 16, yanlis: 4, net: 14.67, kazanimlar: [] },
  },
  {
    exam_name: 'LGS Deneme Sınavı 1',
    date: '2024-04-15',
    class: '8-B',
    student_no: 201,
    student_name: 'Fatma Demir',
    toplam_dogru: 65,
    toplam_yanlis: 25,
    toplam_net: 56.67,
    toplam_puan: 380,
    turkce: { dogru: 15, yanlis: 5, net: 13.33, kazanimlar: [] },
    tarih: { dogru: 7, yanlis: 3, net: 6, kazanimlar: [] },
    din: { dogru: 7, yanlis: 3, net: 6, kazanimlar: [] },
    ing: { dogru: 8, yanlis: 2, net: 7.33, kazanimlar: [] },
    mat: { dogru: 12, yanlis: 8, net: 9.33, kazanimlar: [] },
    fen: { dogru: 16, yanlis: 4, net: 14.67, kazanimlar: [] },
  },
  // Deneme 2
  {
    exam_name: 'LGS Deneme Sınavı 2',
    date: '2024-05-01',
    class: '8-A',
    student_no: 101,
    student_name: 'Ayşe Yılmaz',
    toplam_dogru: 78,
    toplam_yanlis: 12,
    toplam_net: 74,
    toplam_puan: 440,
    turkce: { dogru: 19, yanlis: 1, net: 18.67, kazanimlar: [] },
    tarih: { dogru: 9, yanlis: 1, net: 8.67, kazanimlar: [] },
    din: { dogru: 9, yanlis: 1, net: 8.67, kazanimlar: [] },
    ing: { dogru: 9, yanlis: 1, net: 8.67, kazanimlar: [] },
    mat: { dogru: 16, yanlis: 4, net: 14.67, kazanimlar: [] },
    fen: { dogru: 16, yanlis: 4, net: 14.67, kazanimlar: [] },
  },
  {
    exam_name: 'LGS Deneme Sınavı 2',
    date: '2024-05-01',
    class: '8-A',
    student_no: 102,
    student_name: 'Mehmet Kaya',
    toplam_dogru: 82,
    toplam_yanlis: 8,
    toplam_net: 79.33,
    toplam_puan: 465,
    turkce: { dogru: 20, yanlis: 0, net: 20, kazanimlar: [] },
    tarih: { dogru: 10, yanlis: 0, net: 10, kazanimlar: [] },
    din: { dogru: 9, yanlis: 1, net: 8.67, kazanimlar: [] },
    ing: { dogru: 10, yanlis: 0, net: 10, kazanimlar: [] },
    mat: { dogru: 17, yanlis: 3, net: 16, kazanimlar: [] },
    fen: { dogru: 16, yanlis: 4, net: 14.67, kazanimlar: [] },
  },
  {
    exam_name: 'LGS Deneme Sınavı 2',
    date: '2024-05-01',
    class: '8-B',
    student_no: 201,
    student_name: 'Fatma Demir',
    toplam_dogru: 68,
    toplam_yanlis: 22,
    toplam_net: 60.67,
    toplam_puan: 395,
    turkce: { dogru: 16, yanlis: 4, net: 14.67, kazanimlar: [] },
    tarih: { dogru: 8, yanlis: 2, net: 7.33, kazanimlar: [] },
    din: { dogru: 8, yanlis: 2, net: 7.33, kazanimlar: [] },
    ing: { dogru: 8, yanlis: 2, net: 7.33, kazanimlar: [] },
    mat: { dogru: 12, yanlis: 8, net: 9.33, kazanimlar: [] },
    fen: { dogru: 16, yanlis: 4, net: 14.67, kazanimlar: [] },
  },
    {
    exam_name: 'LGS Deneme Sınavı 2',
    date: '2024-05-01',
    class: '8-C',
    student_no: 301,
    student_name: 'Ali Veli',
    toplam_dogru: 85,
    toplam_yanlis: 5,
    toplam_net: 83.33,
    toplam_puan: 480,
    turkce: { dogru: 20, yanlis: 0, net: 20, kazanimlar: [] },
    tarih: { dogru: 10, yanlis: 0, net: 10, kazanimlar: [] },
    din: { dogru: 10, yanlis: 0, net: 10, kazanimlar: [] },
    ing: { dogru: 10, yanlis: 0, net: 10, kazanimlar: [] },
    mat: { dogru: 18, yanlis: 2, net: 17.33, kazanimlar: [] },
    fen: { dogru: 17, yanlis: 3, net: 16, kazanimlar: [] },
  },
];
